version: '3.1'

services:

  db:
    build: .
    container_name: nestjs-clean
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nestjs-clean
